name: Bug Report
description: Report a bug. Please provide enough information so that we can reproduce the problem.
title: "Bug: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        This form is for reporting technical issues.
        If you have a question or you're looking for support, please visit [Roots Discourse](https://discourse.roots.io/).

  - type: dropdown
    id: terms
    attributes:
      label: Terms
      description: |
        1. I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
        2. This request is not a duplicate of an existing issue
        3. I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
        4. I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
        5. This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community
      options:
        - Yes, all of the above are true.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        #### What's wrong?

        #### What have you tried?

        #### What insights have you gained?

        #### Possible solutions

        #### Temporary workarounds
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Non-reproducible issues may be immediately closed as not actionable.
        Please provide reproduction steps as detailed as possible.
      value: |
        1.
        1.
        1.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      placeholder: What actually happens?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output.
      render: shell

  - type: input
    id: versions
    attributes:
      label: Versions
      description: You can get this information from referencing `CHANGELOG.md`. If you know, please provide the Git commit SHA. Also, please include the OS and what version of the OS you’re running.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
