blank_issues_enabled: false
contact_links:
  - name: 💬 Community Forum
    url: https://discourse.roots.io
    about: Ask questions and discuss with other Roots users
  - name: 💬 Discord Chat
    url: https://github.com/sponsors/roots
    about: Sponsor us on GitHub and join our Discord server
